name: Build Documentation

on:
  pull_request:
    branches-ignore:
    - release/0.11.0

jobs:
  build_documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Install arrow-ank-gradle and arrow-ank
      run: |
        ./gradlew :arrow-ank:publishToMavenLocal
        ./gradlew :arrow-ank-gradle:publishToMavenLocal
    - name: Add arrow-docs module
      run: sed -i "s/modules {/modules {\\ndocs {\\n_ 'docs'\\n_ 'examples'\\n}/g" settings.gradle
    - name: Dokka
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: |
        set -ex
        ./gradlew dokka
    - name: Run Ank
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: |
        set -ex
        ./gradlew :arrow-docs:runAnk
